POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "username": "max",
  "password": "password123"
}

> {% client.global.set("auth_token", response.body.Token); %}

#####
POST http://localhost:8080/api/media/16/favorite
Authorization: Bearer {{auth_token}}
